baseURL: https://jeronimo-blog.netlify.app/
languageCode: en-us
title: Portfolio Website for Jeronimo Fuentes
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: A quick look into my life, interests, and background  
    title: Jeronimo Fuentes' Webpage
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: example@domain.com
        title: jerofw@gmail.com
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: 000 000 000
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: \# Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: #fa-twitter
        label: #Twitter
        url: #https://www.twitter.com
      - icon: #fa-facebook
        label: #Facebook
        url: #https://www.facebook.com
      - icon: #fa-instagram
        label: #Instagram
        url: #https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/jeronimofuentes99
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jeronimof/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Homework 2 Data Analytics
        url: blogs/ciao
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: My CV
        url: blogs/cv
      - name: My Interests
        url: blogs/extracurriculars
      - name: Finance Articles
        url: blogs/int_art
    menu: Menu
    subtitle: 
    title: Jeronimo Fuentes
  tiles:
    enable: yes
    showcase:
      - image: bocconicampus.jpg
        subtitle: List and link to courses from my Undergraduate Degree
        title: Undergraduate Studies
        url: blogs/undergraduate
      - image: t-campus.jpg
        subtitle: Description and relevant links about my Masters experience
        title: Graduate Studies
        url: blogs/graduate
      - image: Rcoding.jpg
        subtitle: Coursework from Data Analytics for Finance Course
        title: Relevant Data Science Coursework
        url: blogs/ciao
      - image: swimming.jpg
        subtitle: What I enjoy outside the classroom
        title: Extracurricular Activities
        url: blogs/extracurriculars
      - image: financial-times.webp
        subtitle: Some articles I find interesting from Finance / Business press
        title: Interesting Articles
        url: blogs/int_art
      - image: Fotocv.png
        subtitle: My Resume
        title:  Curriculum-Vitae
        url: blogs/cv
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Welcome to my personal website. The goal of this site is to bring my CV format to the 21st century and make a interactive site that showcases by background, achievements, interests, and knowledge areas. Moreover, you can find below the links to my different social media accounts. Additionally, feel free to reach out to me using the message box below."
    title: Website Preview
    url: blogs
